### ISSUE TITLE
Don't work in a 3.3.0 with "sub-domain"

### ISSUE THREAD

**Issue by ludovicandrieux** [rgtk/redmine_impersonate#2]
Hi,

We have a redmine 3.3.0 at this URL : http://mydomain.com/redmine/...
When we try the impersonate link, we are rediect to page 404 because URL become http://mydomain.com/redmine/redmine/...

Ludovic

**Comment by nounder** [comment]
Thank you for letting me know. I will look into it today.

**Comment by nounder** [comment]
It turned out to be a core bug for some versions: Redmine didn't prepend root directory to URLs inside hook. I fixed it and now everything works flawlessly on Redmine 2.x and 3.x.

Please download new version of `redmine_impersonate` and enjoy!

Thanks for your contribution, Ludovic.

**Comment by ludovicandrieux** [comment]
Hi,

I just tried 0.10.0 and the bug is still here.
When i come from http://mydomain.com/redmine/users/18 and i click on "Impersonate", i go to http://mydomain.com/redmine/redmine/admin/impersonation?user_id=18

If i try to remoce one /redmine i get this url http://mei.cnp.testenligne.net/redmine/admin/impersonation?user_id=18 but it doesn't work too. Same 404 error.

I use "Redmine Edit Issue Author" from you which works fine.

Ludovic

**Comment by nounder** [comment]
I tested it again in on Redmine instance which is mapped to subdirectory and everything seems to work.

Do you know how is your instance configured? Is it redirected to `/redmine` directory via proxy using web server (like apache or ngnix)?

When you manually remove "/redmine" from URL, your browser respond with 404 which is correct. Visiting this URL should be only possible when clicking "Impersonate" button.

If you can don't map your instance to subdirectory, it should be in the root. I suggest you to use subdomain for example which is always a good idea. From my experience, some Redmine plugins have issues which subdirectory configuration.
